apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: client
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: client
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: letsencrypt-prod
  labels:
    app: client
spec:
  rules:
  - host: client.com
    http:
      paths:
      - path: /
        backend:
          serviceName: client
          servicePort: 80
  tls:
  - hosts:
    - client.com
    secretName: client-com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets: 
      - name: registry-credentials
      containers:
      - name: web
        env:
          - name: "AUTH0_DOMAIN"
            value: "<AUTH0_DOMAIN>"
          - name: "AUTH0_CLIENT_ID"
            value: "<CLIENT_ID>"
          - name: "SERVER_URL"
            value: "http://client:8080"
          - name: "CONNECTIONS"
            value: "<CONNECTIONS>"
        imagePullPolicy: Always
        image: registry.gitlab.com/client:<COMMIT_HASH>
        ports:
        - containerPort: 80
